### ISSUE TITLE
--release get crash when compiled with sold on macOS

### ISSUE THREAD

**Issue by Mon-ius** [bluewhalesystems/sold#55]
project toml release config
```toml
[profile.release]
lto = true
strip = true
panic = 'abort'
opt-level = 3
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
```

`RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=sold" cargo +nightly build --release`

Error with 

```bash
error: failed to run custom build command for `crossbeam-utils v0.8.20`
(signal: 11, SIGSEGV: invalid memory reference)
```

It's very wired that, similar compile config in Linux with `mold` works normal, 

`RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=mold" cargo +nightly build --release`
